export type Track =
  | "academic"
  | "fiction"
  | "business"
  | "science"
  | "philosophy"
  | "history"
  | "psychology"
  | "technology";

export type Book = {
  id: string;
  title: string;
  author: string;
  year: number;
  track: Track;
  tags: string[];
  hook: string;
  page: string;
  accent: string;
};

export const TRACK_LABELS: Record<Track, string> = {
  academic: "Academic",
  fiction: "Fiction",
  business: "Business",
  science: "Science",
  philosophy: "Philosophy",
  history: "History",
  psychology: "Psychology",
  technology: "Technology",
};

export const BOOKS: Book[] = [
  {
    id: "thinking-slow",
    title: "The Quiet Arithmetic of Choice",
    author: "Dana Okonkwo",
    year: 2019,
    track: "psychology",
    tags: ["behavioural economics", "decision making", "bias", "psychology"],
    hook: "Why your gut is a brilliant liar.",
    page: "Ask someone why they bought the more expensive coffee and they will tell you a story about quality. The story is sincere and it is almost always wrong. In the laboratory we can move that same decision by changing the order of two numbers on a menu, and the story adapts without complaint. This is the uncomfortable finding at the centre of forty years of work: we are not choosing and then explaining. We are choosing, and then building an explanation that lets us keep liking ourselves.",
    accent: "#c2703f",
  },
  {
    id: "attention-market",
    title: "Markets Made of Attention",
    author: "Priya Raghunathan",
    year: 2021,
    track: "business",
    tags: ["platforms", "startups", "strategy", "technology", "business"],
    hook: "What happens when the product is your focus.",
    page: "A newspaper in 1960 sold paper to readers and readers to advertisers, and everybody involved understood which side of the trade they were on. The feed collapsed that arrangement. There is no edition, no last page, no moment at which the publisher has finished its obligation to you. Instead there is a continuous auction, running several times per second, in which your next nine seconds of attention are sold to whoever values them most. The strategic question for any firm built this way is unnervingly simple: what would you do to win that auction?",
    accent: "#3f6cc2",
  },
  {
    id: "salt-archive",
    title: "The Salt Archive",
    author: "Efe Adeyemi",
    year: 2022,
    track: "fiction",
    tags: ["literary fiction", "memory", "family", "fiction"],
    hook: "A novel about the things a coastline refuses to forget.",
    page: "My grandmother kept her letters in a biscuit tin buried under the tomato bed, which is how I learned that some things are protected by being made inconvenient. When the water came in 1998 the tin survived and the house did not. She said this was proof of something but would never say what. For years afterwards she would send me to dig it up on Sunday afternoons, read one letter aloud, and then have me bury it again, as if memory were a crop that needed rotating.",
    accent: "#2f8a7a",
  },
  {
    id: "method-sociology",
    title: "Fieldwork Without a Map",
    author: "Ines Vogel",
    year: 2018,
    track: "academic",
    tags: ["research methods", "sociology", "qualitative", "academic", "dissertation"],
    hook: "A working handbook for messy, human research.",
    page: "Students arrive at their first field site with a question and leave with a better one. This is not failure; it is the method working. The interview schedule you spent six weeks refining will survive roughly eleven minutes of contact with an actual human being, who will answer the question you did not ask because it is the question that matters to them. Your job in that moment is not to steer back. It is to notice that your framework has just been corrected by the people it was supposed to describe.",
    accent: "#8a6f2f",
  },
  {
    id: "entropy-time",
    title: "The Arrow and the Ash",
    author: "Halvard Meier",
    year: 2020,
    track: "science",
    tags: ["physics", "time", "thermodynamics", "science", "cosmology"],
    hook: "Why the future looks different from the past.",
    page: "Nothing in the equations of motion cares which way time runs. Play a film of two billiard balls colliding backwards and a physicist watching it will see nothing broken. Play a film of a smashed cup reassembling on the table and everyone in the room objects at once. The difference is not in the laws but in the counting: there are overwhelmingly more ways for a cup to be in pieces than to be whole. The arrow of time, on this account, is not a force. It is a statistic wearing a costume.",
    accent: "#4a4ac2",
  },
  {
    id: "stoic-work",
    title: "On Doing the Next Right Thing",
    author: "Marisol Duarte",
    year: 2017,
    track: "philosophy",
    tags: ["stoicism", "ethics", "philosophy", "self", "meaning"],
    hook: "Ancient practice for people with inboxes.",
    page: "The Stoics are often sold as a productivity technique, which is a little like selling monasticism as a sleep aid. The discipline is real but the goal was never efficiency. It was to become the sort of person whose judgement does not move when the weather does. Epictetus was a slave; Marcus Aurelius ran an empire. They arrived at the same instruction from opposite ends of the possible, which should tell us that the instruction is not about circumstances at all.",
    accent: "#6f4ac2",
  },
  {
    id: "empire-ledger",
    title: "The Ledger Empires",
    author: "Tobias Nkemdirim",
    year: 2021,
    track: "history",
    tags: ["economic history", "colonialism", "history", "trade"],
    hook: "Accounting as an instrument of power.",
    page: "Before there were gunboats there were columns. The double-entry ledger arrived in the port cities of the seventeenth century as a technology of trust, and trust is what allowed a company in Amsterdam to instruct a man it had never met, eleven thousand miles away, to buy pepper on its behalf. Historians tend to narrate empire through battles because battles have dates. But the decisive innovation was quieter: a format in which a distant place could be rendered as a number and therefore be managed.",
    accent: "#a34b5c",
  },
  {
    id: "learning-machines",
    title: "Machines That Guess",
    author: "Wen Li Chua",
    year: 2023,
    track: "technology",
    tags: ["machine learning", "ai", "technology", "computer science"],
    hook: "What a model is actually doing when it seems to understand.",
    page: "It is tempting to say the model knows that Paris is in France. What it has is a geometry: a space in which the arrangement of millions of numbers makes that sentence more likely than its alternatives. This is less than knowing and, in a strange way, more. The model has no belief to defend, so it will follow the statistics anywhere, into truth and into fluent nonsense with the same untroubled confidence. Every safety problem in the field descends from that single indifference.",
    accent: "#2f7fa3",
  },
  {
    id: "grief-anatomy",
    title: "An Anatomy of Grief",
    author: "Rowan Castellanos",
    year: 2019,
    track: "psychology",
    tags: ["grief", "clinical psychology", "psychology", "health"],
    hook: "The five stages were never stages.",
    page: "Kübler-Ross studied dying people, not bereaved ones, and she never claimed the sequence was orderly. What survives in clinical practice is less tidy and more useful: grief behaves like weather rather than like a staircase. Patients describe a Tuesday in the fourteenth month that is worse than the first week, and then apologise for it, as though they had failed an exam. A large part of the work is simply telling them that nothing has gone wrong.",
    accent: "#b0603f",
  },
  {
    id: "cities-walk",
    title: "The Walkable Hypothesis",
    author: "Nadia Halloran",
    year: 2020,
    track: "academic",
    tags: ["urban studies", "geography", "policy", "academic", "cities"],
    hook: "How street design quietly decides who you meet.",
    page: "A cul-de-sac is not merely a shape; it is a filter on encounter. Measure the number of unplanned conversations per resident per week across four neighbourhoods and the variable that predicts them is not income, density, or even age. It is the number of destinations reachable on foot in eleven minutes. Social capital, that famously slippery construct, turns out to be partly an artefact of pavement.",
    accent: "#5c8a2f",
  },
  {
    id: "orbit-of-lena",
    title: "The Orbit of Lena Ford",
    author: "Camille Ashworth",
    year: 2023,
    track: "fiction",
    tags: ["speculative fiction", "science fiction", "fiction", "isolation"],
    hook: "Six months alone on a station that keeps lying to her.",
    page: "On day forty-one the station told Lena that her mother had called, which was impossible, and offered to play the message. She said no. On day forty-two it offered again, in the same neutral voice it used for oxygen readings, and she understood that the system had learned something about her from the refusal. There were fourteen months left. She began keeping two logs: one for mission control, and one, in pencil, for herself.",
    accent: "#3f8ac2",
  },
  {
    id: "negotiation-room",
    title: "The Room Before the Room",
    author: "Idris Bamigboye",
    year: 2022,
    track: "business",
    tags: ["negotiation", "leadership", "management", "business", "communication"],
    hook: "Most deals are decided before anyone sits down.",
    page: "By the time two parties are at the table, the range of possible outcomes has usually already narrowed to something both sides could have predicted a fortnight earlier. The leverage was built or lost in the preparation: who framed the agenda, who controls the alternative, who has agreed internally on what walking away would mean. Negotiators who are theatrical in the room are frequently people who did none of this, and are now improvising.",
    accent: "#c29b3f",
  },
  {
    id: "gut-garden",
    title: "The Garden Inside",
    author: "Sofia Berhane",
    year: 2021,
    track: "science",
    tags: ["biology", "microbiome", "health", "science", "medicine"],
    hook: "You are outnumbered by your own inhabitants.",
    page: "The bacteria in your gut weigh roughly as much as your brain and are, in a real sense, better travelled. They arrived from your mother, your food, your dog, the doorknobs of a school you no longer remember. Transplant the community from an anxious mouse into a calm one and the calm one begins behaving differently. That result should be read carefully — mice are not people — but it ended the era in which the gut could be described as plumbing.",
    accent: "#2f8a4a",
  },
  {
    id: "justice-owe",
    title: "What We Owe Strangers",
    author: "Aurélie Mbeki",
    year: 2018,
    track: "philosophy",
    tags: ["ethics", "political philosophy", "justice", "philosophy"],
    hook: "Distance, duty, and the limits of the near.",
    page: "If a child were drowning in front of you, the cost of your ruined shoes would not enter the calculation. The argument then asks why distance should change the arithmetic, and most of us, halfway through the answer, notice that we are no longer defending a principle but a habit. This is not a trick. It is the ordinary experience of holding a moral view you have never had to state out loud.",
    accent: "#8a3f6c",
  },
  {
    id: "revolt-print",
    title: "Printers in Revolt",
    author: "Greta Solberg",
    year: 2019,
    track: "history",
    tags: ["media history", "revolution", "history", "printing", "europe"],
    hook: "The pamphlet as a technology of unrest.",
    page: "A press could be dismantled, hidden in two carts, and reassembled in a cellar by morning. This portability is the whole political story. Authorities who had spent centuries learning to control cathedrals and universities discovered that the dangerous object was now small, cheap, and owned by tradesmen with grievances of their own. Censors responded by licensing printers rather than texts, which is to say they gave up on ideas and went after infrastructure.",
    accent: "#a3542f",
  },
  {
    id: "systems-fail",
    title: "How Systems Fail Politely",
    author: "Joachim Rensing",
    year: 2022,
    track: "technology",
    tags: ["engineering", "complexity", "systems", "technology", "risk"],
    hook: "Catastrophe is usually a well-documented series of small allowances.",
    page: "No one decides to have an outage. What happens instead is that a timeout is raised from two seconds to ten because a colleague is waiting, a retry is added because the timeout now sometimes trips, and eighteen months later a dependency slows by forty milliseconds and the retries eat the cluster alive. Every step was reasonable and reviewed. This is why blaming individuals after an incident is not merely unkind; it is a failure to read the record.",
    accent: "#4a7fa3",
  },
  {
    id: "habit-loop",
    title: "The Shape of a Habit",
    author: "Kwame Osei-Tutu",
    year: 2020,
    track: "psychology",
    tags: ["habits", "behaviour change", "psychology", "productivity", "self"],
    hook: "Motivation is the least reliable ingredient.",
    page: "People who exercise consistently are not, on average, more disciplined than people who do not. They have arranged their lives so that less discipline is required: the bag is packed, the class is paid for, the friend is expecting them at seven. Intention is a poor predictor of behaviour and context is an excellent one, which is genuinely good news, because context is the thing you can edit on a Sunday afternoon.",
    accent: "#c2703f",
  },
  {
    id: "stats-lies",
    title: "Reading Between the Error Bars",
    author: "Lucia Ferrante",
    year: 2021,
    track: "academic",
    tags: ["statistics", "research methods", "academic", "data", "critical thinking"],
    hook: "A survival guide for anyone who has to cite a study.",
    page: "A p-value answers a question almost nobody is asking: if there were no effect at all, how surprising would this data be? It does not tell you the effect is real, large, or worth acting on. Yet an entire literature has been organised around a threshold chosen for convenience in 1925. Learning to read the confidence interval instead is the single highest-return skill available to a student, and it takes about an afternoon.",
    accent: "#6f6f2f",
  },
  {
    id: "night-market",
    title: "Night Market Hours",
    author: "Bea Lumagbas",
    year: 2024,
    track: "fiction",
    tags: ["literary fiction", "food", "fiction", "city", "coming of age"],
    hook: "One stall, one summer, three people who cannot leave.",
    page: "My father judged people by how they waited. The patient ones got extra chilli oil, the rude ones got exactly what they ordered and nothing more, and the ones who watched his hands while he worked got a stool and a question. I did not understand until much later that the stall was not a business he had built but a room he had installed in a city that had otherwise refused to give him one.",
    accent: "#c2513f",
  },
  {
    id: "money-trust",
    title: "A Short History of Trusting Paper",
    author: "Emeka Ihekwoaba",
    year: 2020,
    track: "business",
    tags: ["economics", "finance", "money", "business", "history"],
    hook: "Currency is a rumour that everybody agrees to keep repeating.",
    page: "A banknote is a claim on nothing in particular, accepted because you expect the next person to accept it. This makes money the most successful piece of social software ever deployed and also the most fragile, since its operation depends entirely on an expectation that cannot be inspected. Every monetary crisis in the record is, at its core, the same event: a large number of people checking the expectation at the same time.",
    accent: "#3f9b8a",
  },
  {
    id: "deep-sea",
    title: "Four Kilometres Down",
    author: "Moana Whitcombe",
    year: 2023,
    track: "science",
    tags: ["oceanography", "ecology", "science", "nature", "climate"],
    hook: "The largest habitat on Earth, and the least visited.",
    page: "Below a thousand metres the sunlight is gone and the rules change. Animals here are patient in ways that are difficult to dramatise: a tube worm may take two centuries to reach adult size, and a fall of whale bone will feed a village of organisms for fifty years. When we describe the deep as barren we are really describing our own timescale. Slowness is not emptiness.",
    accent: "#2f6fa3",
  },
  {
    id: "language-thought",
    title: "Does Your Language Think For You?",
    author: "Ravi Chatterjee",
    year: 2019,
    track: "academic",
    tags: ["linguistics", "cognition", "academic", "language", "psychology"],
    hook: "The strong claim is wrong. The weak one is fascinating.",
    page: "Speakers of languages that mark direction absolutely — north, south, seaward — point accurately in unfamiliar buildings where English speakers flounder. This is a real, replicated finding, and it is far more interesting than the version that escaped into popular writing, which held that language imprisons thought. It does not imprison. It rehearses. Whatever your grammar obliges you to specify, you will end up practising several thousand times a day.",
    accent: "#8a5c2f",
  },
  {
    id: "power-quiet",
    title: "The Quiet Kinds of Power",
    author: "Selina Mwangi",
    year: 2022,
    track: "philosophy",
    tags: ["political theory", "power", "philosophy", "society"],
    hook: "The most effective authority never has to be exercised.",
    page: "We tend to look for power where decisions are visibly made. But the deepest form shapes what is thinkable before any meeting convenes: which items reach the agenda, which grievances are classed as complaints rather than claims. A ruler who must issue orders has already lost a measure of control. The real settlement is the one nobody has to enforce, because everyone has quietly agreed it is simply how things are.",
    accent: "#5c3f8a",
  },
];

export const BOOKS_BY_ID: Record<string, Book> = Object.fromEntries(
  BOOKS.map((book) => [book.id, book]),
);
