// Ported verbatim from the Perlego onboarding prototype.
export type PBook = {
  g: string; t: string; ex: string[]; p: number; a: string; y: string; c: string; b: string; r: string;
};
export type PTopic = { k: string; label: string; icon: string; ac: string };
export type PScriptTurn = { q: string; replies: string[] };

export const BOOKS: PBook[] = [
    {g:'zfuOEAAAQBAJ',t:'Sapiens',ex:["Seventy thousand years ago, Homo sapiens was an unremarkable animal minding its own business in a corner of Africa. Everything that followed — empires, money, religion, the stock exchange — grew out of a change in how that animal talked.","Harari's argument is that shared fictions are the species' real technology. Nations, companies and human rights exist because enough people agree to behave as if they do.","What follows is a history of three revolutions: cognitive, agricultural and scientific, and the question of whether any of them made us happier."],p:464,a:'Yuval Noah Harari',y:'2011',c:'History & Politics',b:'A sweeping account of how one species of ape came to dominate the planet, told through cognition, agriculture and empire.',r:'Because you chose history'},
    {g:'KAjBXwAACAAJ',t:'Thinking, Fast and Slow',ex:["Two systems share the work of thinking. One is fast, automatic and almost always on; the other is slow, effortful and reluctant to be summoned.","Most of the time the fast system runs the show and it is remarkably good at it. The trouble starts where it is confident and wrong.","Kahneman spent four decades cataloguing those failures with Amos Tversky, and this book is the plain account of what they found."],p:499,a:'Daniel Kahneman',y:'2011',c:'Psychology',b:'The two systems that shape judgment and decision-making, from fast intuition to slow deliberate reasoning.',r:'A common first read in behavioural science'},
    {g:'6aMfnwEACAAJ',t:'Thinking in Systems',ex:["A system is more than the sum of its parts: it is a set of elements connected in a way that produces behaviour of its own.","Stocks, flows, feedback loops. Once you can see them, the same shapes turn up in a bathtub, a national economy and a warming planet.","Meadows wrote this primer to make that vocabulary ordinary, and to show where a small push changes everything."],p:240,a:'Donella H. Meadows',y:'2008',c:'Science & Environment',b:'A short primer on seeing the feedback loops behind climate, cities, economies and everything else that misbehaves.',r:'Because you chose science'},
    {g:'GraMEAAAQBAJ',t:'Algorithms to Live By',ex:["Computer scientists spend their careers on problems humans face daily: when to stop looking, how to order a shelf, what to do with limited time.","The mathematics of optimal stopping says look at the first 37 per cent, then take the next thing better than anything you have seen.","The book runs through sorting, caching, scheduling and chance, and argues that the best algorithm is often not the cleverest one."],p:368,a:'Brian Christian and Tom Griffiths',y:'2016',c:'Technology & Society',b:'What computer science says about when to stop looking, how to sort your life and when to leave things to chance.',r:'Sits between your science and psychology picks'},
    {g:'vo5REQAAQBAJ',t:'Atomic Habits',ex:["Habits are the compound interest of self-improvement. One per cent better every day is barely visible on the day and decisive over a year.","The unit of change is not the goal but the system: cue, craving, response, reward, each one an editable part.","Clear's method is to make the behaviour you want obvious, attractive, easy and satisfying, and to do the reverse for the rest."],p:320,a:'James Clear',y:'2018',c:'Psychology',b:'A practical framework for building habits in small increments, grounded in behavioural research.',r:'Widely read alongside your picks'},
    {g:'vi-loAEACAAJ',t:'The Sixth Extinction',ex:["Five times in the history of life, diversity has collapsed. The sixth is under way now, and its cause is reading this sentence.","Kolbert reports from the field: a Panamanian frog rescue, an acidifying bay off Naples, a limestone quarry holding the end of the Ordovician.","The science of extinction is young. It took until the nineteenth century for anyone to accept that species vanish at all."],p:336,a:'Elizabeth Kolbert',y:'2014',c:'Science & Environment',b:'Field reporting on the mass extinction now under way, and the science that first recognised extinction at all.',r:'Because you chose science'},
    {g:'_mRHrgEACAAJ',t:'The Silk Roads',ex:["The centre of the world was never Europe. For most of recorded history it lay across the belt of land connecting east and west.","Along those routes travelled silk and slaves, plague and paper, Buddhism, Islam and the ideas that made the modern state.","Frankopan rewrites the familiar chronology by standing in Samarkand rather than London and asking what the view looks like from there."],p:672,a:'Peter Frankopan',y:'2015',c:'History & Politics',b:'A history of the world told from its centre of gravity, the trade routes running east to west.',r:'Because you chose history'},
    {g:'BL2OEAAAQBAJ',t:'The Scout Mindset',ex:["A soldier defends a position. A scout draws the map. Most of us think like soldiers and call it reasoning.","The scout mindset is the habit of wanting to know what is actually there, even when the answer is inconvenient.","Galef sets out the small, practical tests that reveal which mode you are in, and how to change the incentives that keep you in the wrong one."],p:288,a:'Julia Galef',y:'2021',c:'Philosophy & Humanities',b:'On seeing clearly rather than defending a position, and the habits that make accurate thinking possible.',r:'Pairs with behavioural science'},
    {g:'KGCNEAAAQBAJ',t:'The Alignment Problem',ex:["Machine learning systems do not follow instructions. They infer what we want from examples, and the examples carry everything we failed to say.","A hiring model learns the prejudices in a decade of hiring. A vision model learns that the grass in the photograph means cow.","Christian follows the researchers trying to close the gap between what we ask for and what we meant."],p:496,a:'Brian Christian',y:'2020',c:'Technology & Society',b:'How machine learning systems acquire our values, and what happens in the gap where they do not.',r:'Recent science writing'},
    {g:'PT22DwAAQBAJ',t:'Braiding Sweetgrass',ex:["A botanist and a member of the Citizen Potawatomi Nation, Kimmerer was trained to ask how a plant works, not what it has to say.","This book braids the two: scientific observation, indigenous teaching, and a grammar in which the world is animate rather than inert.","The argument is reciprocity. What we take from the land creates an obligation, and gratitude is the beginning of paying it."],p:408,a:'Robin Wall Kimmerer',y:'2013',c:'Science & Environment',b:'A botanist braids indigenous knowledge and plant science into a case for reciprocity with the living world.',r:'Because you chose science'},
    {g:'ivmMEAAAQBAJ',t:'Why Nations Fail',ex:["Nogales, Arizona and Nogales, Sonora share a climate, a culture and a name. One side is three times richer than the other.","The difference is institutions: whether they include most people in economic life, or extract from them for the benefit of a few.","Acemoglu and Robinson test that claim across five centuries, from the Glorious Revolution to the Congo, and against every rival explanation."],p:544,a:'Daron Acemoglu and James A. Robinson',y:'2012',c:'History & Politics',b:'An argument that institutions, not geography or culture, decide which countries prosper.',r:'History with an economics angle'},
    {g:'heCtnQEACAAJ',t:'The Design of Everyday Things',ex:["If a door needs a sign telling you to push, the door has failed, and the failure is the designer's rather than yours.","Norman's vocabulary — affordances, signifiers, mapping, feedback — turns everyday frustration into something diagnosable.","The book is thirty years old and still the fastest way to start noticing why objects behave the way they do."],p:368,a:'Don Norman',y:'1988',c:'Technology & Society',b:'The foundational text on why objects confuse us, and how affordances and feedback fix them.',r:'A staple in your subjects'}
  ];

export const TOPICS: PTopic[] = [
    {k:'science',label:'Science',icon:'atom',ac:'#1ad3b0'},{k:'fiction',label:'Fiction',icon:'book-open',ac:'#ed6fff'},
    {k:'nonfiction',label:'Non-fiction',icon:'library',ac:'#714cf9'},{k:'business',label:'Business',icon:'trending-up',ac:'#ff5400'},
    {k:'history',label:'History',icon:'landmark',ac:'#ffd400'},{k:'philosophy',label:'Philosophy',icon:'scroll',ac:'#714cf9'},
    {k:'psychology',label:'Psychology',icon:'brain',ac:'#ed6fff'},{k:'economics',label:'Economics',icon:'line-chart',ac:'#ff5400'},
    {k:'politics',label:'Politics',icon:'gavel',ac:'#3327ec'},{k:'technology',label:'Technology',icon:'cpu',ac:'#affc40'},
    {k:'art',label:'Art & design',icon:'palette',ac:'#ffd400'},{k:'environment',label:'Environment',icon:'leaf',ac:'#1ad3b0'}
  ];

export const ALL: string[] = ['KAjBXwAACAAJ','FrOMEAAAQBAJ','BBMlzgEACAAJ','BfTQr6tpn0wC','R42aBAAAQBAJ','vo5REQAAQBAJ','heCtnQEACAAJ','DOyJDQAAQBAJ','1fbingEACAAJ','prDZAQAACAAJ','_2ZRzQEACAAJ','y1ONEAAAQBAJ','GraMEAAAQBAJ','3gOOEAAAQBAJ','KGCNEAAAQBAJ','tKr0QwAACAAJ','zfuOEAAAQBAJ','ivmMEAAAQBAJ','_mRHrgEACAAJ','OwVrSMQPPowC','PMLnbx06vOEC','RaWMEAAAQBAJ','PT22DwAAQBAJ','vi-loAEACAAJ','6aMfnwEACAAJ','1vcF0QEACAAJ','Phj2jZwYDKcC','H6EIBufi6hwC','BL2OEAAAQBAJ','2Jd5DwAAQBAJ'];

export const CAPTIONS: string[] = ['Reading across 1,204 science titles','Weighing recent publications higher','Matching to your reading level','Pulling twelve to show you'];

export const SCRIPT: PScriptTurn[] = [
    {q:'What are you reading for at the moment?',replies:['I\u2019m studying for a course','Work, mostly','Curiosity \u2014 no plan']},
    {q:'Good. Is there a question you keep circling back to?',replies:['Why societies change','How people actually decide','How the climate system works']},
    {q:'And how do you like it written \u2014 close to the research, or a story you can follow?',replies:['Keep it close to the research','Tell it as a story','A bit of both']}
  ];

export const PLANS = [
  { k: 'monthly', name: 'Monthly', perDay: '\u00a30.39', billed: 'Billed \u00a312 per month', note: 'Full access, month to month. Stop whenever you like.', badge: '' },
  { k: 'termly', name: 'Termly', perDay: '\u00a30.33', billed: 'Billed \u00a340 every 4 months', note: 'Covers one term of reading in a single payment.', badge: '' },
  { k: 'yearly', name: 'Yearly', perDay: '\u00a30.26', billed: 'Billed \u00a396 every year', note: 'The lowest daily price \u2014 a third less than monthly.', badge: 'Best value' },
];

export const CAT_TINT: Record<string, string> = { 'History & Politics': '#fff2b8', Psychology: '#fbdcff', 'Science & Environment': '#c7f5ea', 'Technology & Society': '#e6ffc9', 'Philosophy & Humanities': '#e4e8fe', 'Business & Economics': '#ffddcc' };

export const LIST_NAMES: Record<string, string> = { 'History & Politics': 'How societies change', Psychology: 'How people decide', 'Science & Environment': 'Systems and the living world', 'Technology & Society': 'Technology and its consequences', 'Philosophy & Humanities': 'Thinking clearly', 'Business & Economics': 'How markets behave' };

export const LIST_WHY: Record<string, string> = { 'History & Politics': 'Runs from the long view to a single turning point, so each book sets up the next.', Psychology: 'Starts with the research everyone cites, then the applications built on it.', 'Science & Environment': 'Begins with the way systems fail, then the field reporting that shows it happening.', 'Technology & Society': 'Design first, then what happens when those systems scale.', 'Philosophy & Humanities': 'Short reads on judgment, best taken between the heavier books.', 'Business & Economics': 'Institutions first, then the strategy that operates inside them.' };

export function cover(g: string, z?: number) {
  return 'https://books.google.com/books/content?id=' + g + '&printsec=frontcover&img=1&zoom=' + (z || 2) + '&source=gbs_api';
}
